name: mootools-zencoding
author: ju1ius
category: Native
tags: [element, zen coding, parser, html generator]
docs: http://ju1ius.github.com/mootools-zencoding
demo: http://ju1ius.github.com/mootools-zencoding
